from fastapi.templating import Jinja2Templates
from . import runtime_settings as rs

templates = Jinja2Templates(directory="app/templates")

# Translation dictionary
TRANSLATIONS = {
    "Zaloguj się": "Sign In",
    "Zaloguj się do panelu zarządzania ogrodem": "Log in to the garden management panel",
    "Nazwa użytkownika": "Username",
    "Hasło": "Password",
    "Mój ogród": "My Garden",
    "Zabezpieczono przez Ogrodnik AI.": "Secured by Gardener AI.",
    "Wyloguj": "Log Out",
    "Ogrodnik AI": "Gardener AI",
    "Ustawienia": "Settings",
    "Dashboard": "Dashboard",
    "Ogród": "Garden",
    "Zapisano ustawienia.": "Settings saved.",
    "Zapisz": "Save",
    "Te ustawienia mają priorytet nad zmiennymi z .env i są trzymane w lokalnej bazie": "These settings have priority over .env variables and are stored in a local database",
    "SQLite (bez szyfrowania) - wygodne w Dockerze, bo nie wymaga przebudowy obrazu": "SQLite (unencrypted) - convenient in Docker, as it doesn't require rebuilding the image",
    "ani restartu kontenera po zmianie klucza.": "or restarting the container after key changes.",
    "Podgląd ogrodu": "Garden Preview",
    "Dodaj roślinkę": "Add Plant",
    "Nazwa roślinky / gatunek": "Plant name / species",
    "Wybierz zdjęcie roślinki...": "Choose plant photo...",
    "Dodaj": "Add",
    "Zidentyfikuj roślinę i zdiagnozuj problemy z AI": "Identify plant and diagnose issues with AI",
    "Wybierz zdjęcie do analizy...": "Choose photo for analysis...",
    "Analizuj": "Analyze",
    "Brak roślin w ogrodzie.": "No plants in the garden.",
    "Data dodania:": "Added date:",
    "Wynik analizy AI:": "AI analysis result:",
    "Zidentyfikowano jako:": "Identified as:",
    "Stan zdrowia:": "Health status:",
    "Zalecenia:": "Recommendations:",
    "Stan nawadniania": "Irrigation Status",
    "Kosiarka": "Lawn Mower",
    "Ostatnia aktualizacja:": "Last update:",
    "Temperatura:": "Temperature:",
    "Wilgotność:": "Humidity:",
    "Opady (dzisiaj):": "Precipitation (today):",
    "Wiatr:": "Wind:",
    "Zachmurzenie:": "Cloud cover:",
    "Nasłonecznienie:": "Solar radiation:",
    "Stan:": "Status:",
    "Bateria:": "Battery:",
    "Planowane nawadnianie dzisiaj:": "Planned irrigation today:",
    "Ostatnie nawadnianie:": "Last irrigation:",
    "Sekcja": "Section",
    "Czas trwania": "Duration",
    "minut": "minutes",
    "Brak danych z Home Assistant (brak integracji).": "No data from Home Assistant (missing integration).",
    "Brak danych z Hydrawise (brak integracji).": "No data from Hydrawise (missing integration).",
    "Uruchom kosiarkę": "Start Mower",
    "Zatrzymaj kosiarkę": "Stop Mower",
    "Zaparkuj kosiarkę (dock)": "Dock Mower",
    "Uruchom nawadnianie ręczne": "Start manual irrigation",
    "Wstrzymaj nawadnianie (wszystkie sekcje)": "Suspend irrigation (all sections)",
    "Nazwa": "Name",
    "Akcje": "Actions",
    "Usuń": "Delete",
    "Analiza rośliny": "Plant Analysis",
    "Identyfikacja rośliny": "Plant Identification",
    "Wynik identyfikacji": "Identification Result",
    "Nazwa (prawdopodobna):": "Name (probable):",
    "Pewność AI:": "AI confidence:",
    "Opis:": "Description:",
    "Wymagania wodne:": "Water requirements:",
    "Wymagania świetlne:": "Light requirements:",
    "Pielęgnacja:": "Care:",
    "Brak danych do analizy. Prześlij zdjęcie.": "No data for analysis. Please upload a photo.",
    "Błąd podczas analizy obrazu przez AI.": "Error during image analysis by AI.",
    "Błąd podczas identyfikacji rośliny.": "Error during plant identification.",
    "Język": "Language",
    "Język / Language": "Language",
    "Podlewania (14 dni)": "Waterings (14 days)",
    "Koszenia (14 dni)": "Mowings (14 days)",
    "Pogoda": "Weather",
    "ładowanie...": "loading...",
    "Opady vs. dni (7 dni)": "Precipitation vs days (7 days)",
    "Wnioski AI (Gemini)": "AI Insights (Gemini)",
    "Odśwież teraz": "Refresh now",
    "Wygenerowano": "Generated",
    "automatycznie": "automatically",
    "ręcznie": "manually",
    "na podstawie ostatnich": "based on the last",
    "dni": "days",
    "Brak jeszcze zapisanych wniosków - scheduler generuje je automatycznie co 24h": "No insights saved yet - the scheduler generates them automatically every 24h",
    "(wymaga GEMINI_API_KEY w .env), albo kliknij \"Odśwież teraz\".": "(requires GEMINI_API_KEY in .env), or click \"Refresh now\".",
    "Dodaj akcję ogrodową": "Add garden action",
    "Nawożenie": "Fertilizing",
    "Sadzenie": "Planting",
    "Przycinanie": "Pruning",
    "Oprysk / ochrona": "Spraying / Protection",
    "Podlewanie ręczne": "Manual watering",
    "Inne": "Other",
    "Opis": "Description",
    "Produkt (np. nawóz X)": "Product (e.g. fertilizer X)",
    "Dawka (np. 50g/m2)": "Dosage (e.g. 50g/m2)",
    "Strefa ogrodu": "Garden zone",
    "Ostatnie akcje": "Recent actions",
    "Brak akcji - dodaj pierwszą po lewej.": "No actions - add the first one on the left.",
    "Analizuję...": "Analyzing...",
    "Brak odpowiedzi.": "No response.",
    "Błąd": "Error",
    "Brak zdjęcia mapy - wgraj zdjęcie/szkic ogrodu poniżej, albo kliknij tutaj, żeby dodać rośliny bez tła (pozycje względne).": "No map photo - upload a photo/sketch of the garden below, or click here to add plants without a background (relative positions).",
    "Wybrana pozycja na mapie:": "Selected position on map:",
    "brak - kliknij na mapie": "none - click on map",
    "Zmień zdjęcie/szkic mapy": "Change map photo/sketch",
    "Wgraj": "Upload",
    "Rozpoznaj rośliny ze zdjęcia (AI)": "Recognize plants from photo (AI)",
    "Analizuj": "Analyze",
    "Nazwa (np. Lawenda)": "Name (e.g. Lavender)",
    "Nazwa łacińska (opcjonalnie)": "Latin name (optional)",
    "Strefa (opcjonalnie)": "Zone (optional)",
    "Notatki (opcjonalnie)": "Notes (optional)",
    "Zapisz na mapie": "Save on map",
    "Najpierw kliknij pozycję na mapie po lewej.": "First click on the map position on the left.",
    "Rośliny w ogrodzie": "Plants in the garden",
    "Strefa:": "Zone:",
    "dodano przez AI": "added by AI",
    "dodano ręcznie": "added manually",
    "usuń": "delete",
    "Wybierz najpierw zdjęcie.": "Please select a photo first.",
    "Analizuję zdjęcie...": "Analyzing photo...",
    "Znaleziono": "Found",
    "propozycji - kliknij pozycję na mapie, potem \"Użyj\".": "suggestions - click position on map, then \"Use\".",
    "Użyj": "Use",
    "Teraz kliknij pozycję na mapie po lewej i zapisz formularz.": "Now click the position on the map on the left and save the form.",
    "fertilizing": "Fertilizing",
    "planting": "Planting",
    "pruning": "Pruning",
    "pest_control": "Spraying / Protection",
    "watering_manual": "Manual Watering",
    "other": "Other",
}

def translate(text: str) -> str:
    lang = rs.get_value("language") or "pl"
    if lang == "en":
        return TRANSLATIONS.get(text, text)
    return text

# Register translation helper
templates.env.globals["t"] = translate
